no_retry = true
remote_topgrades = ["cems.local"]

[git]
repos = [
	"~/.dotfiles",
	"~/r/*",
	"~/w/*/*",
	"~/gh/*/*",
]

[commands]
"Rust Analyzer" = "cd ~/r/rust-analyzer && cargo xtask install --server"
"Neovim Nightly" = "cd /tmp && wget https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.deb && sudo dpkg -i nvim-linux64.deb ; rm nvim-linux64.deb"

[firmware]
upgrade = true
