edit_mode = "vi"
path = ["/home/thomas/.local/bin", "/snap/bin/", "/home/thomas/.nvm/versions/node/v12.12.0/bin", "/home/thomas/.cargo/bin", "/usr/local/bin", "/usr/bin", "/bin", "/usr/local/games", "/usr/games", "/home/thomas/.fzf/bin"]
prompt = "emplace catch $(history | last); starship prompt"

[env]
ALACRITTY_LOG = "/tmp/Alacritty-96608.log"
COLORTERM = "truecolor"
DBUS_SESSION_BUS_ADDRESS = "unix:path=/run/user/1000/bus"
DESKTOP_SESSION = "i3"
DISPLAY = ":0"
GDMSESSION = "i3"
GPG_AGENT_INFO = "/run/user/1000/gnupg/S.gpg-agent:0:1"
HOME = "/home/thomas"
I3SOCK = "/run/user/1000/i3/ipc-socket.1852"
LANG = "en_US.UTF-8"
LANGUAGE = "en_US:en"
LOGNAME = "thomas"
NVM_BIN = "/home/thomas/.nvm/versions/node/v12.12.0/bin"
NVM_CD_FLAGS = ""
NVM_DIR = "/home/thomas/.nvm"
OLDPWD = "/home/thomas"
PWD = "/home/thomas/r/emplace"
QT_ACCESSIBILITY = "1"
QT_SCALE_FACTOR = "2"
RUSTC_WRAPPER = "sccache"
SHELL = "/bin/bash"
SHLVL = "1"
SSH_AGENT_PID = "1876"
SSH_AUTH_SOCK = "/tmp/ssh-GxXJnwzdnkYx/agent.1852"
TERM = "xterm-256color"
USER = "thomas"
WINDOWID = "102760451"
XAUTHORITY = "/home/thomas/.Xauthority"
XDG_CURRENT_DESKTOP = "i3"
XDG_GREETER_DATA_DIR = "/var/lib/lightdm/data/thomas"
XDG_RUNTIME_DIR = "/run/user/1000"
XDG_SEAT = "seat0"
XDG_SEAT_PATH = "/org/freedesktop/DisplayManager/Seat0"
XDG_SESSION_CLASS = "user"
XDG_SESSION_DESKTOP = "i3"
XDG_SESSION_ID = "2"
XDG_SESSION_PATH = "/org/freedesktop/DisplayManager/Session0"
XDG_SESSION_TYPE = "x11"
XDG_VTNR = "7"
_ = "/home/thomas/.cargo/bin/nu"
_fzf_orig_completion_awk = "complete -F %s awk #_longopt"
_fzf_orig_completion_cat = "complete -F %s cat #_longopt"
_fzf_orig_completion_cd = "complete -o nospace -F %s cd #_cd"
_fzf_orig_completion_cp = "complete -F %s cp #_longopt"
_fzf_orig_completion_diff = "complete -F %s diff #_longopt"
_fzf_orig_completion_du = "complete -F %s du #_longopt"
_fzf_orig_completion_ftp = "complete -F %s ftp #_known_hosts"
_fzf_orig_completion_grep = "complete -F %s grep #_longopt"
_fzf_orig_completion_head = "complete -F %s head #_longopt"
_fzf_orig_completion_ld = "complete -F %s ld #_longopt"
_fzf_orig_completion_less = "complete -F %s less #_longopt"
_fzf_orig_completion_ln = "complete -F %s ln #_longopt"
_fzf_orig_completion_ls = "complete -F %s ls #_longopt"
_fzf_orig_completion_mv = "complete -F %s mv #_longopt"
_fzf_orig_completion_pushd = "complete -o nospace -F %s pushd #_cd"
_fzf_orig_completion_rm = "complete -F %s rm #_longopt"
_fzf_orig_completion_rmdir = "complete -F %s rmdir #_longopt"
_fzf_orig_completion_sed = "complete -F %s sed #_longopt"
_fzf_orig_completion_sort = "complete -F %s sort #_longopt"
_fzf_orig_completion_tail = "complete -F %s tail #_longopt"
_fzf_orig_completion_tee = "complete -F %s tee #_longopt"
_fzf_orig_completion_telnet = "complete -F %s telnet #_known_hosts"
_fzf_orig_completion_uniq = "complete -F %s uniq #_longopt"
_fzf_orig_completion_wc = "complete -F %s wc #_longopt"
