*google*
*facebook*
*twitter*
*ampproject*
*gstatic*
*apple*
#*cloudflare*
*tfbnw*
*fbcdn*
*fburl*
*instagram*
*waze*
*msn*
*windows*
*pinterest*
*pinimg*
*twimg*
t.co
*atlassian*
#*microsoft*
#*office*
*discord*
