repo_directory = "/home/thomas/.local/share/emplace"

[repo]
url = "git@github.com:tversteeg/dotfiles.git"
branch = "master"
file = ".emplace"

[[symlink]]
source = "emplace.toml"
destination = "~/.config/emplace.toml"

[[symlink]]
source = "bashrc"
destination = "~/.bashrc"

[[symlink]]
source = "config.vim"
destination = "~/.config/nvim/init.vim"

[[symlink]]
source = "config.i3"
destination = "~/.config/i3/config"

[[symlink]]
source = "topgrade.toml"
destination = "~/.config/topgrade.toml"

# [[symlink]]
# source = "firefox-userchome.css"
# destination = "~/.mozilla/firefox/*.default*/chrome/userChrome.css"
# 
# [[symlink]]
# source = "firefox-vars.css"
# destination = "~/.mozilla/firefox/*.default*/chrome/vars.css"
