repo_directory = "/home/thomas/.local/share/emplace"

[[symlink]]
destination = "~/.config/emplace.toml"
source = "emplace.toml"

[[symlink]]
destination = "~/.bashrc"
source = "bashrc"

[[symlink]]
destination = "~/.config/nvim/init.vim"
source = "config.vim"

[[symlink]]
destination = "~/.config/i3/config"
source = "config.i3"

[[symlink]]
destination = "~/.config/topgrade.toml"
source = "topgrade.toml"

[[symlink]]
destination = "~/.mozilla/firefox/**/chrome/userChrome.css"
source = "firefox-userchrome.css"

[[symlink]]
destination = "~/.mozilla/firefox/**/chrome/vars.css"
source = "firefox-vars.css"

[[symlink]]
destination = "i3status-rust.toml"
source = "/home/thomas/.config/i3status-rust/config.toml"

[repo]
branch = "master"
file = ".emplace"
url = "git@github.com:tversteeg/dotfiles.git"
