shell = "bash -c '{}'"

[[item]]
file = "~/.dotfiles/alacritty.toml"
template = "alacritty"
subtemplate = "default-256"

[[item]]
file = "~/.dotfiles/dunstrc"
template = "dunst"

[[item]]
file = "~/.dotfiles/waybar-colors.css"
template = "waybar"
rewrite = true

[[item]]
file = "~/.dotfiles/config.fish"
template = "fzf"
subtemplate = "fish"

[[item]]
file = "~/.dotfiles/zellij-theme.kdl"
template = "zellij"
