#!/bin/bash

# Exit when something goes wrong
set -e

UNSTAGED=$(git diff --name-only --diff-filter=ACM)
if [ -n "$UNSTAGED" ]; then
	echo "There are unstaged changes, please add them manually before altering the history"
	exit 1
fi

LAST_COMMIT=$(git log -1 --pretty=%B)
if [[ $LAST_COMMIT == "Merge branch"* || $LAST_COMMIT == "Pull"* ]]; then
	echo "Last commit was a merge commit, rebasing onto first non-merge commit before that:"
	FIRST_NONE_MERGE_COMMIT=$(git log -1 --invert-grep --grep='^Merge')
	echo "$FIRST_NONE_MERGE_COMMIT"

	COMMIT_HASH=$(git log -1 --format="%H" --invert-grep --grep='^Merge')
	git commit --fixup $COMMIT_HASH
	# Hack so the rebase prompt won't be opened
	GIT_SEQUENCE_EDITOR=true git rebase -i --autosquash $COMMIT_HASH^
else
	git commit --amend
fi
