[[language]]
name = "rust"
language-servers = ["rust-analyzer", "typos"]

[language-server.typos]
command = "typos-lsp"

[language-server.rust-analyzer]
timeout = 60

[language-server.rust-analyzer.config]
check.command = "clippy"
cargo.features = "all"
procMacro.ignored.leptos_macro = ["server"]

[[language]]
name = "javascript"
formatter = { command = "deno", args = ["fmt", "-", "--ext", "js" ] }
auto-format = true

[[language]]
name = "json"
formatter = { command = "deno", args = ["fmt", "-", "--ext", "json" ] }

[[language]]
name = "markdown"
formatter = { command = "deno", args = ["fmt", "-", "--ext", "md" ] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "deno", args = ["fmt", "-", "--ext", "ts" ] }
auto-format = true

[[language]]
name = "jsx"
formatter = { command = "deno", args = ["fmt", "-", "--ext", "jsx" ] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = "deno", args = ["fmt", "-", "--ext", "tsx" ] }
auto-format = true

[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
#language-server = { command = "helm_ls", args = "serve" }
auto-format = true
formatter = { command = "prettier", args = ["--parser", "yaml"] }
