[icons]
icons = "material-nf"

[[block]]
block = "sound"

[[block]]
block = "music"
format = " $icon $cur.eng(w:1)/$avail.eng(w:1) {$combo.str(max_w:15,rot_interval:0.5) $play $next |}"
if_command = "hostname | grep -q pc"

[[block]]
block = "disk_space"
[[block.click]]
button = "left"
cmd = "thunar"

[[block]]
block = "memory"

[[block]]
block = "cpu"
format = " $icon $barchart $utilization"
format_alt = " $icon $frequency{ $boost|} "

[[block]]
block = "load"

[[block]]
block = "temperature"
format = " $icon $max"

[[block]]
block = "net"

[[block]]
block = "docker"
if_command = "hostname | grep -q cems"

#[[block]]
#block = "kdeconnect"

[[block]]
block = "backlight"
if_command = "hostname | grep -q cems"

[[block]]
block = "battery"
if_command = "hostname | grep -q cems"

[[block]]
block = "time"
format = " $icon $timestamp.datetime(f:'%a %d/%m %R') "
[[block.click]]
button = "left"
cmd = "thunderbird -calendar"

[[block]]
block = "time"
if_command = "hostname | grep -q pc"
format = " $icon $timestamp.datetime(f:%R) "
timezone = "Asia/Ho_Chi_Minh"
[block.icons_overrides]
time = "\uf005"

[[block]]
block = "weather"
format = " $icon $temp  $humidity  $wind_kmh.eng(w:1)"
service = { name = "openweathermap", api_key = "f3fae1d7eda4929ec1f10ebdf797f46a", city_id = "2754064", units = "metric" }
[[block.click]]
button = "left"
cmd = "xdg-open https://www.buienradar.nl/weer/hilversum/nl/2754064/5daagse"
