"$schema" = 'https://starship.rs/config-schema.json'
format = "$all"

[hostname]
ssh_symbol = " "

[directory]
repo_root_style = "underline"

[package]
symbol = " "
version_format = "${raw}"

[rust]
symbol = " "
version_format = "${raw}"

[kubernetes]
disabled = false
contexts = [
  { context_pattern = "gke_crux-automation_europe-west4-a_crux-production", context_alias = "prod" }
]

[gcloud]
symbol = " "
format = "on [$symbol$project]($style) "

[conda]
symbol = " "

[python]
symbol = " "

[lua]
symbol = "󰢱 "

[git_metrics]
added_style = "bold blue"
format = "[+$added]($added_style)/[-$deleted]($deleted_style) "

[git_branch]
ignore_branches = ["master", "main"]

[memory_usage]
disabled = false
