[misc]
no_retry = true
skip_notify = true
remote_topgrades = ["cems.local"]

[git]
pull_only_repos = ["~/.dotfiles", "~/r/*", "~/w/*/*", "~/gh/*/*"]

[commands]
"i3status" = "cd ~/r/i3status-rust/ && cargo install --path . --locked && ./install.sh"
"helix" = "cd ~/r/helix/ && cargo install --path helix-term --locked"
"dotter" = "cd ~/.dotfiles && dotter"
"nerdfonts" = "cd ~/r/nerd-fonts && cp -R patched-fonts/* ~/.local/share/fonts/ && fc-cache -f -v"
"zola" = "cd ~/r/zola/ && cargo install --path . --locked"
"niri" = "cd ~/r/niri/ && cargo build --release && sudo cp target/release/niri /usr/bin/ && sudo cp resources/niri-ession /usr/bin/ && sudo cp resources/niri.desktop /usr/share/wayland-sessions/ && cp resource/niri-portals.conf /usr/share/xdg-desktop-portal/ && sudo cp resources/niri.service /usr/lib/systemd/user/"

[firmware]
upgrade = true
