[[language]]
name = "rust"
#language-server = { command = "rustup", args = ["run", "nightly", "rust-analyzer"] }

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "vue"
auto-format = true
file-types = ["vue"]
injection-regex = "vue"
language-server = { command = "vue-language-server", args = ["--stdio"] }
roots = ["package.json"]
scope = "text.html.vue"

[language.config.typescript]
tsdk = "/usr/local/lib/node_modules/typescript/lib"