[icons]
name = "material-nf"

# [[block]]
# block = "github"
# hide_if_total_is_zero = true

[[block]]
block = "sound"

[[block]]
block = "music"
format = "$combo.rot-str(15) $play $next|"
hide_when_empty = true

[[block]]
block = "disk_space"

[[block]]
block = "memory"

[[block]]
block = "cpu"
format = "$barchart.str() $utilization.eng()"

# [[block]]
# block = "nvidia_gpu"
# show_utilization = false
# label = ""

[[block]]
block = "net"
device = "enp39s0"

[[block]]
block = "kdeconnect"
hide_disconnected = true
device_id = "70a73b2b0c97a9bb"

[[block]]
block = "time"
format = "%a %d/%m %R"

[[block]]
block = "time"
format = "%R"
timezone = "Asia/Ho_Chi_Minh"
[block.icons_overrides]
time = "\uf005"

[[block]]
block = "weather"
format = "$temp  $humidity  $wind_kmh"
service = { name = "openweathermap", api_key = "f3fae1d7eda4929ec1f10ebdf797f46a", city_id = "2754064", units = "metric" }

# Start flavours
# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Summerfruit Light by Christopher Corley (http://christop.club/)

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#FFFFFF"
idle_fg = "#101010"
info_bg = "#1FAAAA"
info_fg = "#FFFFFF"
good_bg = "#00C918"
good_fg = "#FFFFFF"
warning_bg = "#ABA800"
warning_fg = "#FFFFFF"
critical_bg = "#FF0086"
critical_fg = "#FFFFFF"
# The rest of the theme settings are left at default.
# End flavours
