shell = "bash -c '{}'"

[[item]]
file = "~/.config/i3/config"
template = "i3"
subtemplate = "colors"
hook = "i3-msg reload"
# i3 reload temporarily freezes input, so it's marked as not-light
light = false

[[item]]
file = "~/.config/i3status-rust/config.toml"
template = "i3status-rust"

[[item]]
file = "~/.config/alacritty/alacritty.yml"
template = "alacritty"
subtemplate = "default-256"

[[item]]
file = "~/.config/nvim/colors/base16.vim"
template = "vim"
rewrite = true
hook = "reloadnvim"

[[item]]
file = "~/.config/rofi/themes/colors.rasi"
template = "rofi"
rewrite = true

[[item]]
file = "~/.config/dunst/dunstrc"
template = "dunst"

[[item]]
file = "~/.config/hexchat/colors.conf"
template = "hexchat"
rewrite = true

[[item]]
file = "~/.gtkrc-2.0"
template = "gtk2"
subtemplate = "schemes"

[[item]]
file = "~/.Xresources"
template = "xresources"
rewrite = true
