no_retry = true

[git]
repos = [
	"~/.dotfiles",
	"~/r/*",
	"~/w/*/*",
]

[commands]
"Rust Analyzer" = "cd ~/r/rust-analyzer && cargo xtask install --server"
"Helix" = "cd ~/r/helix && cargo install --path helix-term && mkdir -p ~/.config/helix/runtime && cp -R runtime/* ~/.config/helix/runtime/"
