version: "3.7"

services:
        homepage:
                image: ghcr.io/benphelps/homepage:latest
                container_name: homepage
                ports:
                        - 3000:3000
                volumes:
                        - /home/thomas/.config/homepage/:/app/config
                        - /var/run/docker.sock:/var/run/docker.sock 

        searx:
                image: searx/searx
                container_name: searx
                networks:
                        - searx
                ports:
                        - 3001:8080
                volumes:
                        - /home/thomas/searx:/etc/searx
                environment:
                        - BASE_URL=http://serv.local:3001/

networks:
        searx:
                ipam:
                        driver: default
