imports_granularity = "Crate"
reorder_impl_items = true
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
inline_attribute_width = 50
