[misc]
no_retry = true
skip_notify = true

[git]
repos = ["~/.dotfiles", "~/r/*", "~/w/*/*", "~/gh/*/*"]

[commands]
"i3status" = "cd ~/r/i3status-rust/ && cargo install --path . --locked && ./install.sh"
"helix" = "cd ~/r/helix/ && cargo install --path helix-term --locked"
"dotter" = "cd ~/.dotfiles && dotter"

[firmware]
upgrade = true
