#! /bin/sh

if [ ! -x /usr/bin/cmus-remote ];
then
	echo "cmus is not installed."
exit
fi

ARTIST=$( cmus-remote -Q 2>/dev/null | grep ' artist' | cut -d " " -f 3- )
TITLE=$( cmus-remote -Q 2>/dev/null | grep title | cut -d " " -f 3- )
DURATION=$( cmus-remote -Q 2>/dev/null | grep duration | cut -d " " -f 2- )
POSITION=$( cmus-remote -Q 2>/dev/null | grep position | cut -d " " -f 2- )

if [ -z "$DURATION" ];
then
	echo "Nothing playing"
else
	echo "$ARTIST - $TITLE [$POSITION:$DURATION]" | tr '\\' '/' | tr '\n' ' '
fi
