#! /bin/sh

bspc monitor DVI-I-0 -d I II III
bspc monitor DVI-D-0 -d IV V VI VII
bspc monitor DVI-I-1 -d VIII IX X

bspc config border_width        2
bspc config window_gap          12
bspc config top_padding		16
bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a BSPWM_FRAME frame=on

/home/thomas/.config/bspwm/panel/panel &
