#! /bin/sh

bspc monitor DVI-I-0 -d I II III
bspc monitor DVI-D-0 -d IV V VI VII
bspc monitor DVI-I-1 -d VIII IX X

bspc config border_width        4
bspc config window_gap          4
bspc config top_padding			18
bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a Gimp follow=on floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

/home/thomas/.config/bspwm/panel/panel &
