[helpers]

[default]
depends = ["starship", "alacritty", "git", "flavours", "dunst", "pipewire", "scripts", "zellij", "helix", "systemd", "topgrade", "waybar", "qmk", "niri", "wayland", "lemurs", "fuzzel", "atuin", "desktop", "fish", "rust"]

[scripts.files]
"start-zellij-session.sh" = "~/.local/bin/start-zellij-session"

[starship.files]
"starship.toml" = "~/.config/starship.toml"

[alacritty.files."alacritty.toml"]
target = "~/.config/alacritty/alacritty.toml"
type = "template"

[git.files]
gitconfig = "~/.gitconfig"
"ssh_auth_socket.conf" = "~/.config/environment.d/ssh_auth_socket.conf"
"ssh.conf" = "~/.ssh/config"

[flavours.files]
"flavours.toml" = "~/.config/flavours/config.toml"

[font.files]
"fonts.conf" = "~/.config/fontconfig/fonts.conf"
"fontconf.d" = "~/.config/fontconfig/conf.d"

[dunst.files]
dunstrc = "~/.config/dunst/dunstrc"

[neovim.files]
"neovim.lua" = "~/.config/nvim/init.lue"

[helix.files]
"helix-config.toml" = "~/.config/helix/config.toml"
"helix-languages.toml" = "~/.config/helix/languages.toml"

[systemd.files]
systemd = "~/.config/systemd/user"
"/usr/lib/systemd/user/waybar.service" = "~/.config/systemd/user/niri.service.wants/waybar.service"
"/usr/lib/systemd/user/dunst.service" = "~/.config/systemd/user/niri.service.wants/dunst.service"

[pipewire.files]
wireplumber = "~/.config/wireplumber"

[zellij.files]
"zellij.kdl" = "~/.config/zellij/config.kdl"
zellij-layouts = "~/.config/zellij/layouts"

[topgrade.files]
"topgrade.toml" = "~/.config/topgrade.toml"

[topgrade.variables]
remote_upgrades = ""

[waybar.files]
"waybar-style.css" = "~/.config/waybar/style.css"

[waybar.files."waybar-config.json"]
target = "~/.config/waybar/config"
type = "template"

[qmk.files]
"qmk/" = "~/.qmk_firmware/keyboards/ferris/keymaps/tversteeg"

[niri.files]
"niri.kdl" = "~/.config/niri/config.kdl"
"niri-portals.conf" = "~/.config/xdg-desktop-portal/portals.conf"

[niri.files."niri-portals.conf"]
target = "/usr/share/xdg-desktop-portal/niri-portals.conf"
type = "symbolic"
owner = "root"

[wayland.files]
"electron25-flags.conf" = "~/.config/electron25-flags.conf"

[lemurs.files."lemurs/lemurs.pam"]
target = "/etc/pam.d/lemurs"
type = "template"
owner = "root"

[lemurs.files."lemurs/lemurs.service"]
target = "/usr/lib/systemd/system/lemurs.service"
type = "symbolic"
owner = "root"

[lemurs.files."lemurs/lemurs.toml"]
target = "/etc/lemurs/config.toml"
type = "symbolic"
owner = "root"

[lemurs.files."lemurs/niri.sh"]
target = "/etc/lemurs/wayland/niri"
type = "symbolic"
owner = "root"

[fuzzel.files]
"fuzzel.ini" = "~/.config/fuzzel/fuzzel.ini"

[atuin.files]
"atuin.toml" = "~/.config/atuin/config.toml"

[desktop.files]
"desktop/helix.desktop" = "~/.local/share/applications/helix.desktop"
"desktop/aseprite.desktop" = "~/.local/share/applications/aseprite.desktop"

[fish.files]
"config.fish" = "~/.config/fish/config.fish"

[rust.files]
"cargo.toml" = "~/.cargo/config.toml"
