[helpers]

[default]
depends = ["bash", "starship", "alacritty", "git", "flavours", "dunst", "i3", "i3status", "sway", "pipewire", "scripts", "zellij", "helix", "systemd", "searx"]

[scripts.files]
"tv.sh" = "~/.local/bin/tv"
"huion.sh" = "~/.local/bin/huion"
"k8.sh" = "~/.local/bin/k8"
"list-fftabs.sh" = "~/.local/bin/list-fftabs"
"forward-localhost-port.sh" = "~/.local/bin/forward-localhost-port"
"start-zellij-session.sh" = "~/.local/bin/start-zellij-session"

[bash.files]
bashrc = "~/.bashrc"
bash_profile = "~/.bash_profile"

[starship.files]
"starship.toml" = "~/.config/starship.toml"

[alacritty.files]
"alacritty.yml" = "~/.config/alacritty/alacritty.yml"

[git.files]
gitconfig = "~/.gitconfig"

[flavours.files]
"flavours.toml" = "~/.config/flavours/config.toml"

[font.files]
"fonts.conf" = "~/.config/fontconfig/fonts.conf"
"fontconf.d" = "~/.config/fontconfig/conf.d"

[dunst.files]
dunstrc = "~/.config/dunst/dunstrc"

[neovim.files]
"neovim.lua" = "~/.config/nvim/init.lue"

[helix.files]
"helix-config.toml" = "~/.config/helix/config.toml"
"helix-languages.toml" = "~/.config/helix/helix-languages.toml"

[i3.files]
i3config = "~/.config/i3/config"
Xresources = "~/.Xresources"

[i3status.files]
"i3status.toml" = "~/.config/i3status-rust/config.toml"

[searx.files]
"searx.yml" = "~/.config/searx/settings.yml"

[sway.files]
swayconfig = "~/.config/sway/config"

[systemd.files]
systemd = "~/.config/systemd/user"

[pipewire.files]
wireplumber = "~/.config/wireplumber"

[zellij.files]
"zellij.kdl" = "~/.config/zellij/config.kdl"
zellij-layouts = "~/.config/zellij/layouts"
